name: excoffizer
root: ~/dev/excoffizer

#on_project_start:
#  elm install

windows:
  - editor:
      layout: main-vertical
      panes:
        - ls src/*.elm | entr -cdr elm make src/Main.elm --debug --output=elm.js
        - elm reactor
        -
